### ISSUE TITLE
TypeError: CreateListFromArrayLike called on non-object

### ISSUE THREAD

**Issue by ghost** [Tonejs/MidiConvert#92]
Full trace:

```
/home/victor/programs/midi-to-netlogo/node_modules/@tonejs/midi/build/Midi.js:1
(function (exports, require, module, __filename, __dirname) { !function(t,e){if("object"==typeof exports&&"object"==typeof module)module.exports=e();else if("function"==typeof define&&define.amd)define([],e);else{var r=e();for(var n in r)("object"==typeof exports?exports:t)[n]=r[n]}}("undefined"!=typeof self?self:this,function(){return function(t){var e={};function r(n){if(e[n])return e[n].exports;var i=e[n]={i:n,l:!1,exports:{}};return t[n].call(i.exports,i,i.exports,r),i.l=!0,i.exports}return r.m=t,r.c=e,r.d=function(t,e,n){r.o(t,e)||Object.defineProperty(t,e,{enumerable:!0,get:n})},r.r=function(t){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(t,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(t,"__esModule",{value:!0})},r.t=function(t,e){if(1&e&&(t=r(t)),8&e)return t;if(4&e&&"object"==typeof t&&t&&t.__esModule)return t;var n=Object.create(null);if(r.r(n),Object.defineProperty(n,"default",{enu

TypeError: CreateListFromArrayLike called on non-object
    at n.readString (/home/victor/programs/midi-to-netlogo/node_modules/@tonejs/midi/build/Midi.js:1:13060)
    at n.readChunk (/home/victor/programs/midi-to-netlogo/node_modules/@tonejs/midi/build/Midi.js:1:13250)
    at Object.t.exports [as parseMidi] (/home/victor/programs/midi-to-netlogo/node_modules/@tonejs/midi/build/Midi.js:1:13371)
    at t (/home/victor/programs/midi-to-netlogo/node_modules/@tonejs/midi/build/Midi.js:1:7424)
    at Object.<anonymous> (/home/victor/programs/midi-to-netlogo/index.js:3:14)
    at Module._compile (internal/modules/cjs/loader.js:722:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:733:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
```

Code used:

```
const {Midi} = require("@tonejs/midi");
const fs = require("fs")
const midi = Midi(String(fs.readFileSync("./main.mid", "base64")))
```

yes, main.mid is a full valid midi file

**Comment by tambien** [comment]
Does it work if you don't cast the file to a string? 

```javascript
const midi = new Midi(fs.readFileSync("./main.mid"))
```

**Comment by ghost** [comment]
Hello, sorry for the late response. No, I get the same error.

**Comment by tambien** [comment]
I'm unable to recreate this error with any of the midi files i have. Here's an example of the code that i posted running as expected: https://repl.it/repls/LimeUnitedNetwork
